<?php

return [
    'template_vars' => [
        'cache_types' => [
            'config' => 1,
            'layout' => 1,
            'block_html' => 1,
            'collections' => 1,
            'reflection' => 1,
            'db_ddl' => 1,
            'compiled_config' => 1,
            'eav' => 1,
            'customer_notification' => 1,
            'config_integration' => 1,
            'config_integration_api' => 1,
            'full_page' => 1,
            'target_rule' => 1,
            'config_webservice' => 1,
            'translate' => 1,
            'google_product' => 1,
            'vertex' => 1,
        ],
        'database_ssl_verify_cert' => false,
    ],
    'snapshot' => [
        'asset_groups' => [
            'core' => [
                '/captcha',
                '/catalog/category/cache',
                '/catalog/product/cache',
                '/css',
                '/css_secure',
                '/import',
                '/js',
                '/js_secure',
                '/catalog/placeholder/cache',
                '/tmp',
            ],
            'common_modules' => [],
        ],
        'database_table_groups' => [
            // @todo Break up into groups
            // @todo Add sequence tables
            // @todo Add changlog tables?
            // @todo Add tmp tables?
            // @todo Add group to exclude indexes, but do not include in core (It's generally faster to export/import
            //       indexes than it is to reindex them
            'core' => [
                '*_cl',
                '*_debug',
                '*_log',
                '*_lock',
                '*_replica',
                '*_tmp',
                'adminnotification_inbox',
                'admin_passwords',
                'admin_system_messages',
                'admin_user',
                'admin_user_session',
                'api2_acl_attribute',
                'api2_acl_role',
                'api2_acl_rule',
                'api2_acl_user',
                'api_assert',
                'api_role',
                'api_rule',
                'api_session',
                'api_user',
                'catalog_compare_item',
                'catalogsearch_fulltext',
                'core_cache',
                'core_cache_tag',
                'core_session',
                'coupon_aggregated',
                'coupon_aggregated_order',
                'coupon_aggregated_updated',
                'cron_schedule',
                'customer_address_entity',
                'customer_address_entity_datetime',
                'customer_address_entity_decimal',
                'customer_address_entity_int',
                'customer_address_entity_text',
                'customer_address_entity_varchar',
                'customer_entity',
                'customer_entity_datetime',
                'customer_entity_decimal',
                'customer_entity_int',
                'customer_entity_text',
                'customer_entity_varchar',
                'dataflow_batch',
                'dataflow_batch_export',
                'dataflow_batch_import',
                'dataflow_import_data',
                'dataflow_profile_history',
                'dataflow_profile_history',
                'dataflow_session',
                'dataintercept_api_debug',
                'downloadable_link_purchased',
                'downloadable_link_purchased_item',
                'enterprise_catalogpermissions_index',
                'enterprise_catalogpermissions_index_product',
                'enterprise_customer_sales_order',
                'enterprise_customer_sales_order_address',
                'enterprise_customer_quote',
                'enterprise_customer_quote_address',
                'enterprise_customerbalance',
                'enterprise_customerbalance_history',
                'enterprise_customersegment_customer',
                'enterprise_customersegment_event',
                'enterprise_giftcardaccount',
                'enterprise_giftcardaccount_history',
                'enterprise_giftcardaccount_pool',
                'enterprise_giftregistry_data',
                'enterprise_giftregistry_entity',
                'enterprise_giftregistry_item',
                'enterprise_giftregistry_label',
                'enterprise_giftregistry_person',
                'enterprise_giftregistry_type',
                'enterprise_giftregistry_type_info',
                'enterprise_invitation',
                'enterprise_invitation_status_history',
                'enterprise_invitation_track',
                'enterprise_logging_event',
                'enterprise_logging_event_changes',
                'enterprise_logging_event_track',
                'enterprise_reminder_rule',
                'enterprise_reminder_rule_coupon',
                'enterprise_reminder_rule_coupon',
                'enterprise_reminder_rule_website',
                'enterprise_reward',
                'enterprise_reward_history',
                'enterprise_rma',
                'enterprise_rma_grid',
                'enterprise_rma_item_entity',
                'enterprise_rma_item_entity_datetime',
                'enterprise_rma_item_entity_decimal',
                'enterprise_rma_item_entity_int',
                'enterprise_rma_item_entity_text',
                'enterprise_rma_item_entity_text',
                'enterprise_rma_item_form_attribute',
                'enterprise_rma_shipping_label',
                'enterprise_rma_status_history',
                'enterprise_sales_creditmemo_grid_archive',
                'enterprise_sales_invoice_grid_archive',
                'enterprise_sales_order_grid_archive',
                'enterprise_sales_shipment_grid_archive',
                'enterprise_targetrule_index',
                'enterprise_targetrule_index_crosssell',
                'enterprise_targetrule_index_crosssell_product',
                'enterprise_targetrule_index_related',
                'enterprise_targetrule_index_related_production',
                'enterprise_targetrule_index_upsell',
                'enterprise_targetrule_index_upsell_product',
                'enterprise_url_rewrite',
                'enterprise_url_rewrite_category_cl',
                'enterprise_url_rewrite_product_cl',
                'enterprise_url_rewrite_redirect_cl',
                'gift_message',
                'importexport_importdata',
                'log_customer',
                'log_quote',
                'log_summary',
                'log_summary_type',
                'log_url',
                'log_url_info',
                'log_visitor',
                'log_visitor_info',
                'magento_sales_creditmemo_grid_archive',
                'magento_sales_invoice_grid_archive',
                'magento_sales_order_grid_archive',
                'magento_sales_shipment_grid_archive',
                'newsletter_problem',
                'newsletter_queue',
                'newsletter_queue_link',
                'newsletter_queue_store_link',
                'newsletter_subscriber',
                'newsletter_subscriber_backup',
                'oauth_consumer',
                'oauth_nonce',
                'oauth_token',
                'paypal_payment_transaction',
                'paypal_settlement_report',
                'paypal_settlement_report_row',
                'persistent_session',
                'poll_vote',
                'product_alert_price',
                'product_alert_stock',
                'quote',
                'quote_address',
                'quote_address_item',
                'quote_id_mask',
                'quote_item',
                'quote_item_option',
                'quote_payment',
                'quote_preview',
                'quote_shipping_rate',
                'rating_option_vote',
                'rating_option_vote_aggregated',
                'report_compared_product_index',
                'report_event',
                'report_viewed_product_aggregated_daily',
                'report_viewed_product_aggregated_monthly',
                'report_viewed_product_aggregated_yearly',
                'report_viewed_product_index',
                'reporting_counts',
                'reporting_module_status',
                'reporting_orders',
                'reporting_system_updates',
                'reporting_users',
                'review',
                'review_detail',
                'review_entity_summary',
                'review_store',
                'sales_bestsellers_aggregated_daily',
                'sales_bestsellers_aggregated_monthly',
                'sales_bestsellers_aggregated_yearly',
                'sales_billing_agreement',
                'sales_billing_agreement_order',
                'sales_creditmemo',
                'sales_creditmemo_comment',
                'sales_creditmemo_grid',
                'sales_creditmemo_item',
                'sales_invoice',
                'sales_invoice_comment',
                'sales_invoice_grid',
                'sales_invoice_item',
                'sales_order',
                'sales_order_address',
                'sales_order_grid',
                'sales_order_item',
                'sales_order_payment',
                'sales_order_status_history',
                'sales_shipment',
                'sales_shipment_comment',
                'sales_shipment_grid',
                'sales_shipment_item',
                'sales_shipment_track',
                'sales_invoiced_aggregated',
                'sales_invoiced_aggregated_order',
                'sales_order_aggregated_created',
                'sales_order_aggregated_updated',
                'sales_order_tax',
                'sales_order_tax_item',
                'sales_payment_transaction',
                'sales_recurring_profile',
                'sales_recurring_profile_order',
                'sales_refunded_aggregated',
                'sales_refunded_aggregated_order',
                'sales_shipping_aggregated',
                'sales_shipping_aggregated_order',
                'salesrule_coupon',
                'salesrule_coupon_usage',
                'salesrule_customer',
                'sequence_creditmemo_*',
                'sequence_invoice_*',
                'sequence_order_*',
                'sequence_rma_item_*',
                'sequence_shipment_*',
                'sitemap',
                'tag',
                'tag_properties',
                'tag_relation',
                'tag_summary',
                'tax_order_aggregated_created',
                'tax_order_aggregated_updated',
                'UNCLAIMED_PROPERTY',
                'wishlist',
                'wishlist_item',
                'wishlist_item_option',
            ],
            'robofirm/aptos' => [
                'aptos_po',
                'aptos_po_item',
                'aptos_salesaudit_creditmemo',
            ],
            'onepica/avatax' => [
                'op_avatax_log',
                'op_avatax_queue',
            ],
            'onepica/image-cdn' => [
                'op_imagecdn_cache',
            ],
            'eltrino/print-order' => [
                'eltrino_guests_orders',
            ],
            'robofirm/swatch' => [
                'swatch_flat_index',
            ],
            'cybersource/payment-gateway' => [
                'cybersource_api_debug',
                'cybersource_dm_conversion',
                'cybersource_soap_debug',
            ],
            'iwd/all' => [
                'iwd_notification',
            ],
            'aheadworks/rma' => [
                'aw_rma_entity',
                'aw_rma_entity_comments',
            ],
            'aheadworks/automatic-related-products' => [
                'aw_arep_aggregation',
            ],
            'robofirm/process-manager' => [
                'processmanager_dataflow',
                'processmanager_process_log',
            ],
            'bronto/email' => [
                'bronto_customer_queue',
                'bronto_email_log',
                'bronto_emailcapture_queue',
                'bronto_newsletter_queue',
                'bronto_order_queue',
                'bronto_reminder_delivery_log',
                'bronto_reminder_rule_log',
                'bronto_reviews_log',
            ],
            'algolia/algoliasearch-client-php' => [
                'algoliasearch_queue',
            ],
            'amasty/feed' => [
                'am_feed_field_300_backup',
                'am_feed_profile_300_backup',
                'am_feed_template_300_backup',
            ],
            'common_modules' => [
                '@aheadworks/automatic-related-products',
                '@aheadworks/rma',
                '@algolia/algoliasearch-client-php',
                '@amasty/feed',
                '@bronto/email',
                '@cybersource/payment-gateway',
                '@dotdigitalgroup/email',
                '@ebizmarts/abandoned-cart',
                '@ebizmarts/auto-responder',
                '@ebizmarts/magemonkey',
                '@eltrino/print-order',
                '@ess/m2epro',
                '@gomage/feed',
                '@iwd/all',
                '@onepica/avatax',
                '@onepica/image-cdn',
                '@paradoxlabs/authorize-net-cim',
                '@robofirm/aptos',
                '@robofirm/process-manager',
                '@robofirm/swatch',
                '@tbt/rewards',
                '@unirgy/dropship',
                '@unirgy/rma',
                '@webshopapps/logger',
                '@wordpress',
            ],
            'dotdigitalgroup/email' => [
                'email_automation',
                'email_campaign',
                'email_contact',
                'email_importer',
                'email_order',
                'email_quote',
                'email_review',
                'email_wishlist',
            ],
            'ebizmarts/abandoned-cart' => [
                'ebizmarts_abandonedcart_popup',
            ],
            'ess/m2epro' => [
                'm2epro_amazon_item',
                'm2epro_amazon_listing',
                'm2epro_amazon_listing_other',
                'm2epro_amazon_listing_product',
                'm2epro_amazon_listing_product_variation',
                'm2epro_amazon_listing_product_variation_option',
                'm2epro_amazon_order',
                'm2epro_amazon_order_item',
                'm2epro_amazon_processed_inventory',
                'm2epro_buy_item',
                'm2epro_buy_listing',
                'm2epro_buy_listing_other',
                'm2epro_buy_listing_product',
                'm2epro_buy_listing_product_variation',
                'm2epro_buy_listing_product_variation_option',
                'm2epro_buy_order',
                'm2epro_buy_order_item',
                'm2epro_cache_config',
                'm2epro_ebay_item',
                'm2epro_ebay_listing',
                'm2epro_ebay_listing_other',
                'm2epro_ebay_listing_product',
                'm2epro_ebay_listing_product_variation',
                'm2epro_ebay_listing_product_variation_option',
                'm2epro_ebay_order',
                'm2epro_ebay_order_item',
                'm2epro_listing',
                'm2epro_listing_other',
                'm2epro_listing_product',
                'm2epro_listing_product_variation',
                'm2epro_listing_product_variation_option',
                'm2epro_operation_history',
                'm2epro_order',
                'm2epro_order_change',
                'm2epro_order_item',
                'm2epro_order_log',
                'm2epro_order_matching',
                'm2epro_processing_request',
                'm2epro_product_change',
                'm2epro_stop_queue',
                'm2epro_synchronization_log',
                'm2epro_system_log',
            ],
            'ebizmarts/auto-responder' => [
                'ebizmarts_autoresponder_backtostock',
                'ebizmarts_autoresponder_review',
                'ebizmarts_autoresponder_unsubscribe',
                'ebizmarts_autoresponder_visited',
            ],
            'unirgy/rma' => [
                'urma_rma',
                'urma_rma_comment',
                'urma_rma_grid',
                'urma_rma_item',
                'urma_rma_track',
            ],
            'tbt/rewards' => [
                'rewardsref_referral',
                'rewardssocial_customer',
                'rewardssocial_facebook_like',
                'rewardssocial_facebook_share',
                'rewardssocial_google_plusone',
                'rewardssocial_pinterest_pin',
                'rewardssocial_purchase_share',
                'rewardssocial_referral_share',
                'rewardssocial_twitter_tweet',
                'rewards_customer',
                'rewards_customer_index_points',
                'rewards_importer',
                'rewards_reports_indexer_order',
                'rewards_transfer',
                'rewards_transfer_reference',
            ],
            'wordpress' => [
                'wp_commentmeta',
                'wp_comments',
                'wp_contact_form_7',
                'wp_usermeta',
                'wp_users',
            ],
            'unirgy/dropship' => [
                'udropship_batch',
                'udropship_batch_dist',
                'udropship_batch_invrow',
                'udropship_batch_row',
                'udropship_label_batch',
                'udropship_label_shipment',
                'udropship_payout',
                'udropship_payout_adjustment',
                'udropship_payout_row',
                'udropship_po',
                'udropship_po_comment',
                'udropship_po_grid',
                'udropship_po_item',
                'udropship_vendor_statement',
                'udropship_vendor_statement_adjustment',
                'udropship_vendor_statement_row',
                'udshipclass_customer',
            ],
            'paradoxlabs/authorize-net-cim' => [
                'authnetcim_card_exclude',
                'paradoxlabs_stored_card',
            ],
            'ebizmarts/magemonkey' => [
                'magemonkey_api_debug',
                'magemonkey_async_orders',
                'magemonkey_async_subscribers',
                'magemonkey_bulksync_export',
                'magemonkey_bulksync_import',
                'magemonkey_ecommerce360',
                'magemonkey_last_order',
                'magemonkey_mails_sent',
                'mailchimp_errors',
                'mailchimp_sync_batches',
            ],
            'webshopapps/logger' => [
                'wsalogger_log',
            ],
            'gomage/feed' => [
                'gomage_feed_entity',
            ],
        ],
    ],
];
